- name: Add alias to shell
  hosts: localhost
  tasks:
    - name: Check for potential shell config file locations to put function
      stat:
        path: "{{ ansible_env.HOME }}/{{ item }}"
      register: shell_config_files
      loop:
        - .zsh/jajce.zsh
        - .zshrc
        - .bashrc

    - name: Set shell config file
      set_fact:
        shell_config_file: "none"

    - name: Determine shell config file
      set_fact:
        shell_config_file: "{{ item.stat.path }}"
      when: item.stat.exists and shell_config_file == "none"
      loop: "{{ shell_config_files.results }}"

    - name: Fail if no shell config file exists
      fail:
        msg: "None of jajce.zsh, .zshrc, or .bashrc exists. Aborting."
      when: shell_config_file == "none"

    - name: Get current directory
      set_fact:
        current_dir: "{{ lookup('pipe', 'pwd') }}"

    - name: Add volz function to shell config file
      lineinfile:
        path: "{{ shell_config_file }}"
        line: |
          dokku () {
            local loc={{ current_dir }}
            make -f $loc/Makefile create -C $loc CURDIR=$(pwd)
          }
        create: yes
        state: present
